language: android

android:
  components:
  - tools
  - build-tools-23.0.3
  - android-23
  - platform-tools
  - extra-android-support
  - extra-android-m2repository

branches:
  only:
    - master

notifications:
  email: false

script: './gradlew clean build'
