language: android

android:
  components:
  - tools
  - build-tools-23.0.2
  - android-21
  - android-22
  - android-23
  - extra-android-support
  - extra-android-m2repository

branches:
  only:
    - master

notifications:
  email: false

script: './gradlew clean build'
